apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
spec:
  gateways:
    - {{ .Values.virtualService.gateways.name }}
  hosts:
    - {{ .Values.virtualService.hosts.name }}
  http:
    - name: {{ .Values.virtualService.http.name }}
      match:
        - uri:
            prefix: {{ .Values.virtualService.http.prefix }}
      route:
        - destination:
            host: {{ .Values.virtualService.http.destination }}
      corsPolicy:
        allowOrigins:
          - {{ .Values.virtualService.http.allowedHeaders }}
        allowHeaders:
          - Content-Type
          - Authorization
